### ISSUE TITLE
자동차 경주 도메인 개발

### ISSUE THREAD

**Issue by khyeji98** [khyeji98/CarGame#1]
## Description
자동차 경주 도메인 계층 개발

## TODO
- [ ] 입출력 Interface 개발
- [ ] 입출력 UseCase 개발
- [ ] 입력타입 Class 개발
- [ ] 출력타입 Class 개발

## ETC
없음
